spring:
  application:
    name: oauth
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret: 
            scope:
              - user:email
              - read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

server:
  port: 8080